package:
  name: chardet
  version: 4.0.0.9

source:
  path: ./src

requirements:
  run:
    - python

build:
  script: python setup.py install
  noarch: python
  include_recipe: false

test:
  import:
    - chardet
    - chardet.__version__
