{% set name = "pem" %}
{% set version = "21.2.0" %}
{% set sha256 = "c491833b092662626fd58a87375d450637d4ee94996ad9bbbd42593428e93e5a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{name}}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python

test:
  imports:
    - pem

about:
  home: https://github.com/hynek/pem
  license: MIT
  license_file: LICENSE
  summary: Easy PEM file parsing in Python
