# #################################
#
# IMPORTANT: If you make any changes to this file, you must also update
# couchbase-server-black-duck-manifest.yaml in this directory!
#
# #################################

# Extra dependencies that are unique to Linux
dependencies:
  - _libgcc_mutex=0.1
  - ld_impl_linux-64=2.33.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
