# Copyright 2021-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

package:
  name: chardet
  version: 4.0.0.9

source:
  path: ./src

requirements:
  run:
    - python

build:
  script: python setup.py install
  noarch: python
  include_recipe: false

test:
  import:
    - chardet
    - chardet.__version__
